export const landingStyles = `
:root{--ink:#1f2925;--muted:#68756c;--paper:#f7f7f1;--cream:#e9eadf;--accent:#c7e46f;--line:#d8ddd2}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 Arial,sans-serif}a{color:inherit;text-decoration:none}.storefront-page{min-height:100vh}
.landing-header{border-bottom:1px solid var(--line)}.landing-announcement{padding:10px;background:var(--ink);color:#e5efcc;text-align:center;text-transform:uppercase;font-size:10px;letter-spacing:.12em}.landing-announcement span{margin:0 12px;color:var(--accent)}.landing-header-row{display:flex;align-items:center;justify-content:space-between;gap:28px;padding:24px 5vw}.landing-brand{font-size:17px;font-weight:700;letter-spacing:.16em}.landing-brand small{display:block;margin-top:3px;color:var(--muted);font-size:8px;letter-spacing:.45em}.landing-header nav,.landing-actions{display:flex;gap:28px;color:var(--muted);font-size:12px}.landing-actions a:last-child{border-bottom:1px solid var(--ink);padding-bottom:4px;color:var(--ink)}.landing-category-row{display:flex;gap:25px;overflow:auto;padding:0 5vw 16px;color:var(--muted);font-size:11px}.landing-category-row a:first-child{color:var(--ink)}
.landing-hero{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,1fr);gap:7vw;align-items:center;min-height:610px;padding:7vw 9vw}.eyebrow{margin:0 0 22px;color:var(--muted);font-size:11px;letter-spacing:.18em}.landing-copy h1{max-width:650px;margin:0;font-size:clamp(48px,6.2vw,92px);font-weight:400;letter-spacing:-.075em;line-height:.94}.landing-copy h1 em,.section-intro h2 em,.landing-standard h2 em{font-family:Georgia,serif;font-weight:400}.landing-lede{max-width:390px;margin:30px 0;color:var(--muted);font-size:17px}.landing-button{display:inline-flex;gap:38px;align-items:center;background:var(--ink);color:#fff;padding:16px 20px;font-size:11px;letter-spacing:.14em;text-transform:uppercase}.landing-button span{color:var(--accent);font-size:18px}
.landing-art{position:relative;min-height:420px;overflow:hidden;background:#dbe9c2}.landing-sun{position:absolute;right:8%;top:9%;width:72%;aspect-ratio:1;border-radius:50%;background:#f6d9aa;box-shadow:0 0 80px #f6d9aa}.landing-card{position:absolute;left:15%;bottom:12%;display:flex;flex-direction:column;justify-content:space-between;width:175px;height:225px;padding:22px;transform:rotate(-8deg);background:#263a2d;color:#edf1d4;box-shadow:18px 20px 30px #81917755}.landing-card span{color:var(--accent);font-size:12px}.landing-card strong{font-size:28px;line-height:.86;letter-spacing:-.08em}.landing-card small{color:#abc091;font-size:9px;letter-spacing:.14em}.landing-ribbon{display:flex;justify-content:space-around;gap:28px;overflow:hidden;padding:14px 5vw;background:var(--accent);font-size:11px;letter-spacing:.14em;white-space:nowrap}
.landing-collection{padding:92px 5vw}.section-intro{display:flex;align-items:end;justify-content:space-between;gap:30px;margin-bottom:42px}.section-intro h2,.landing-standard h2{margin:0;font-size:56px;font-weight:400;letter-spacing:-.065em;line-height:1}.text-link{display:inline-block;border-bottom:1px solid var(--ink);padding-bottom:5px;font-size:12px}.landing-products{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.landing-product-card{min-width:0}.landing-product-image{aspect-ratio:4/5;overflow:hidden;background:#e6e8df}.landing-product-image img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .45s}.landing-product-card:hover img{transform:scale(1.04)}.landing-product-meta{display:flex;justify-content:space-between;gap:12px;padding-top:14px}.landing-product-meta strong,.landing-product-meta span{display:block}.landing-product-meta strong{font-size:15px;font-weight:400}.landing-product-meta span{margin-top:4px;color:var(--muted);font-size:11px}.landing-product-meta b{font-size:13px;font-weight:400}.landing-empty{color:var(--muted)}.landing-standard{display:grid;grid-template-columns:1fr 2fr;gap:8vw;padding:120px 14vw;background:var(--cream)}.landing-standard h2{font-size:78px}.landing-standard p:not(.eyebrow){max-width:470px;margin:28px 0;color:var(--muted);font-size:18px}
@media(max-width:800px){.landing-header nav{display:none}.landing-header-row{padding:20px 6vw}.landing-actions{gap:14px}.landing-hero{grid-template-columns:1fr;padding:68px 8vw}.landing-art{min-height:320px}.section-intro{display:block}.section-intro .text-link{margin-top:24px}.landing-products{grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.landing-standard{grid-template-columns:1fr;gap:30px;padding:82px 8vw}.landing-standard h2{font-size:58px}.landing-ribbon{justify-content:flex-start}}
`;
